Portfolio: setup and mobile first
Godedict/Portfolio-Setup pull request #1
Opened 2023-05-02 19:16 UTC by Godedict

Portfolio: setup and mobile first was created using the following requirements:
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
Linter should be set up correctly for this repository.
Linter result should be green.
There should be no custom changes to linter config.
Make sure that you used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
README file should be descriptive.
Commit messages should be meaningful.
Pull Request should have a descriptive title explaining what changes are inside.
Pull Request should have a short summary describing introduced changes in more detail.
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):
Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
Pull Request is made from 'feature branch' into the main branch.

2023-05-02 20:18 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @Godedict👋🏽, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitHub Flow correctly 👍🏽
✅ Linter checks passed✔️
✅ Documented your work professionally 👍🏽
✅ Only used HTML & CSS✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 20:18 UTC, Johnadibe commented on index.html
> +  </div>
> - [ ] Great job so far @Godedict👍. I think it would be better if you wrap the headline section in a `section` tag. It represents a generic standalone section of the document, so please kindly use it. You can [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info.😊

> - [ ] Please kindly ensure that the "headline" section stick to the Figma design as much as possible😊.
> 
> Figma design👇:
> 
> ![0-1-figma](https://user-images.githubusercontent.com/40009354/235770138-f50dcc44-8232-4bfb-b9c0-ae93115363c6.PNG)
> 
> Your design👇:
> 
> ![0-1](https://user-images.githubusercontent.com/40009354/235770202-30ff1a06-e592-4a35-b891-6bec4932c7b9.PNG)
>

2023-05-02 20:18 UTC, Johnadibe commented on index.html
> +    <h2 class="logo">My Logo</h2>
> - [ ] It would be better if the logo had a link `<a>` tag. This is for convention, semantics, and user experience(UX). You can 👉[Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info. Please kindly add it😊.

2023-05-02 20:18 UTC, Johnadibe commented on index.html
> +    <a href="#" class="menu-icon"><i class="fa-solid fa-bars"></i></a>
> - [ ] Good job👍. Please kindly wrap the hamburger icon in a `nav` tag. The `nav` tag is for semantics reasons and for good user experience for mobile devices.😊

2023-05-02 20:18 UTC, Johnadibe commented on index.html
> +      </div>
> - [ ] Please kindly group the list of icons using a `ul` tag, and `li` per icon in which each icon has a link `a` tag. This provides semantic meaning to the list of icons and helps assistive technologies, such as screen readers, to better understand the content and present it to users in a more accessible way.😊

2023-05-02 20:18 UTC, Johnadibe commented on style.css
> +}
> - [ ] Good work here👍 I suggest you use Flexbox to align its content. Flexbox is designed to work well with responsive design. You can easily align items horizontally, vertically, or in both directions, and you can also control the spacing between items.😊

2023-05-02 20:18 UTC, Johnadibe commented on style.css
> +  width: 320px;
> Kindly ensure to use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels. This is a good practice because it allows your web design to be flexible and adaptable to different screen sizes and devices.☺

2023-05-03 16:28 UTC, frank1738 requested changes
Hi @Godedict , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 16:28 UTC, frank1738 commented on index.html
> +        <li><a href="#"><img src="./Assets/Peace.jpg" alt="Peace icon"></a></li>
- [ ] Good work up to this point. As requested earlier on making the design match the Figma template as possible, there are some aspects you can improve on.
  - Increase both the left and right padding on your headline section to match the original design
 
![image](https://user-images.githubusercontent.com/98453979/235979315-ce90cb5d-bd01-4c6a-8c5f-d866013ae203.png)

### check out the original design

![image](https://user-images.githubusercontent.com/98453979/235979611-872425dd-1b62-4b7e-a19b-61eeb018bca3.png)

2023-05-03 17:57 UTC, Godedict commented on index.html
> +        <li><a href="#"><img src="./Assets/Peace.jpg" alt="Peace icon"></a></li>
Done and adjusted accordingly. Thank  you.

2023-05-03 18:37 UTC, amon-cofie approved these changes
Hi @Godedict , 👋 

Your project is complete and very impressive 💯!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights

⭐ You could greatly improve your pull request summary stating what you did instead of the requirements.
🚀 You used GitHub flow properly
🚀 You have no linter errors


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 18:37 UTC, amon-cofie commented on style.css
> +}
[OPTIONAL] You have done great work implementing all the changes required by the previous reviewers 👍. Also, your styling is really well done 🔥. However, I believe it would make your code cleaner and less cluttered if you remove CSS properties that are not being used. Over here, the display property is set to inline-block and so the flex-direction is redundant and not being used. I suggest therefore that you remove the flex-direction property just to make your code cleaner and less cluttered. 😉

2023-05-03 18:37 UTC, amon-cofie commented on style.css
> +}
[OPTIONAL] There is on thing I like to do all the time in my CSS and I find that it saves me a lot of time and so I always like to share it when I have the chance 😄. There are some CSS properties that you will find yourself using a lot in your styling and a typical example is the display property of flex. What I like to do is to create a rule with a descriptively named class selector. Then when I write my HTML, I add the rule as a class attribute so that the rule applies to the HTML element and I don't have to rewrite that particular CSS property for every HTML element that uses it. Example: 

```sh
 .flex {
   display: flex;
 }
```

```sh
 <div class="flex">container 1</div>
 <div class="flex">container 2</div>
 <div class="flex">container 3</div>
```

Display of flex gets applied to all 3 divs but I write it once in my CSS. This would not only make your coding faster but will also make your codebase less cluttered and cleaner 😉

2023-05-03 18:45 UTC, Godedict commented on style.css
> +}
wow, that's so smart. I'll try to inculcate it into my work. Thanks

2023-05-03 18:51 UTC, merged