Portfolio: setup and mobile first
Godedict/Portfolio-Setup pull request #2
Opened 2023-05-30 16:02 UTC by Godedict

Portfolio: setup and mobile first was setup using the following requirements:

Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
Linter should be set up correctly for this repository.
Linter result should be green.
There should be no custom changes to linter config.
Make sure that you used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
README file should be descriptive.
Commit messages should be meaningful.
Pull Request should have a descriptive title explaining what changes are inside.
Pull Request should have a short summary describing introduced changes in more detail.
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):
Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
Pull Request is made from 'feature branch' into the main branch.
HTML/CSS requirements
Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
Project requirements
For this project, you should use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)

The 2 sections you need to build for this project are:

the toolbar (or header):
Toolbar

the headline section (right after the header):
Headline

We included a screenshot of Template 1 for reference, but you should follow the template that you chose.

In order to lay out the elements on the page you should use flexbox in all 2 sections.
Only use HTML & CSS (no JavaScript needed)
Your website should look exactly like the design (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).
Implement the button interactions (i.e. hover, etc.).
The website should be responsive, following these breakpoints:
Minimum mobile screen size should be 375px
Minimum desktop screen size should be 768px
Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels

2023-05-30 16:32 UTC, topeogunleye requested changes
Hi @Godedict, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Great UI Design. ✔️ 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="257" alt="image" src="https://github.com/Godedict/Portfolio-Setup/assets/52934128/521fc34e-0f9b-4ae3-a32c-65625f6f6506">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

- [ ] In future pull requests, consider following the recommended branch naming conventions, such as using branch names that reflect the specific feature or task being implemented. This will enhance code organization and collaboration within the team. For example: `added_Portfolio_Setup`


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 16:32 UTC, topeogunleye commented on style.css
- [ ] The color used for the `LET'S CONNECT` button from the Figma design is `#7F8CFF` not `#3567fd`, and a font-weight of `500` not `600`. please kindly make changes to ensure your button uses the font and colors (background and font) defined for the template.

2023-05-30 19:44 UTC, Godedict commented
Thank you, corrections made accordinlgy.

2023-05-30 20:33 UTC, Eternalgratis requested changes
# Status: Required Changes ♻️
Hi @Godedict , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request summary
✅ Linter error checks validated

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-30 20:33 UTC, Eternalgratis commented on style.css
>  }
- Well done on implementing some of the changes requested by the previous reviewer. However, you still need to work on the styling of your p tag. The font size and line weight is different from that of Figma. Kindly make the necessary changes.

2023-05-30 21:34 UTC, Godedict commented on style.css
>  }
Icreasing the font sizes and line heights will force me to use different dimensions (375px x 718px) instead of the responsive dimension i'm currently using (320px x 641px)

2023-05-31 19:50 UTC, Godedict commented on style.css
>  }
font weight and size adjusted accordingly

2023-05-31 19:58 UTC, divinecharlotte approved these changes
# Hello @Godedict      😃 🥳 🎉 🎈 

Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say  👍🏻 ✅ 
### To Highlight 💯

- Descriptive pr👍 
- Linters are passing 👍 
 




## Congratulations! 🎉 

<img src="https://media3.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 21:38 UTC, merged