Portfolio: finish mobile version
Godedict/Portfolio-Setup pull request #3
Opened 2023-06-02 15:52 UTC by Godedict

Portfolio: finish mobile version project was implemented using the following requirement:

- Make sure the content of the "About myself" section is aligned with flexbox.

- In order to lay out the elements in "Works" section you should use CSS Grid and Flexbox combined (it is mandatory that you use both). Use CSS Grid in the main container that contains all of the cards and use Flexbox to lay out an individual card.

- Please use ul and li for categories in "Work" section. Html, CSS, and JavaScript should be list items.

- Please use ul and li for categories in "About myself" section. Languages, Frameworks, and Skills should be list items.

- You don't need to implement the detail modal window that requires JavaScript.

- You must stick to the design as much as possible (e.g., font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

- Implement the button interactions (enable, hover, etc.).

- The website should be responsive, following these breakpoints:

- Minimum mobile screen size should be 375px

- Minimum desktop screen size should be 768px

- Use responsive values in your CSS rules, like percentages (i.e. width: 80%), instead of pixels

2023-06-02 16:19 UTC, souad988 requested changes
Hi @Godedict  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
Design well implemented
Good file structure

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- condensing pr sammary content as it should be short but includes main details 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 16:19 UTC, souad988 commented on index.html
> +  <section class="page-2">
great work done so far 👍🏼  , but the section tag is meant to wrap all project cards as all these items are same 
a section is a semantic element for creating standalone sections in a web page. These sections should be made up of related content, like contact information. The section element should only be used if there isn't a more specific element to represent the related content.


Also this section needs to have a display grid to position it's items, and the background color is diferent than the one udes in figma ==> background: #F7F7F9;

2023-06-02 16:19 UTC, souad988 commented on index.html
> +        <a href="#">See project</a>
Kindly add hover an press effects to all buttons as shown in figma design

2023-06-02 21:09 UTC, Godedict commented on index.html
> +  <section class="page-2">
Done, thank you.

2023-06-02 21:10 UTC, Godedict commented on index.html
> +        <a href="#">See project</a>
Change implemented, thank you.

2023-06-02 22:17 UTC, bienvenuushindi requested changes
### Hi @Godedict      ,

Good job implementing most of the requested  changes!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔


## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.

## [Optional] suggestions:

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-02 22:17 UTC, bienvenuushindi commented on index.html
> +  <section class="card">
:red_circle: Please make sure you apply the grid layout on this section wrapper as [requested by the previous reviewer](https://github.com/Godedict/Portfolio-Setup/pull/3#discussion_r1214569935). This means the CSS display property of this element should be equal to  grid.

2023-06-02 22:17 UTC, bienvenuushindi commented on style.css
>  .buttons {
:red_circle: As [requested by the previous reviewer](https://github.com/Godedict/Portfolio-Setup/pull/3#discussion_r1214570499), Please make sure your button hover state design is the same as the one on Figma. As you can see below there is a huge gap between  the hover state on your Design and the Figma

Your Design
![your](https://github.com/Godedict/Portfolio-Setup/assets/26736582/39911495-adac-4945-b75c-2f888abda70e)

Figma (The second button)
![buttons](https://github.com/Godedict/Portfolio-Setup/assets/26736582/790c0ea2-0ff0-4486-a6bf-bdf4c1ccc20d)

Note: Kindly select the right background color from the Figma Template

2023-06-03 15:18 UTC, Godedict commented on index.html
> +  <section class="card">
Changes made

2023-06-03 15:18 UTC, Godedict commented on style.css
>  .buttons {
changes made.. thanks

2023-06-03 15:41 UTC, Tufahel approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @Godedict :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻

![](https://media0.giphy.com/media/d31w24psGYeekCZy/giphy.gif?cid=ecf05e47zaer8jfqmid0gfxhz2oq4gcjqy2c2aol3ldn6gvl&rid=giphy.gif&ct=g)

:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Correct GitHub flow.
:heavy_check_mark: Commit messages are meaningful.

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.
- You can mail me at [![Mail](https://img.shields.io/badge/Gmail-tufahel96@gmail.com-red?logo=Gmail&logoColor=red&labelColor=black)](mailto:tufahel96@gmail.com) or ask any question at Slack, `Name: Tufahel`

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 15:46 UTC, merged